name: contextchat
description: "An AI chat app with special focus on handling projects context."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  equatable: ^2.0.7
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  http: ^1.6.0
  crypto: ^3.0.7
  collection: ^1.19.1
  path: ^1.9.1
  file_picker: ^10.3.10
  archive: ^4.0.9
  xml: ^6.6.1
  syncfusion_flutter_pdf: ^32.2.9
  google_fonts: ^8.0.2
  lucide_icons_flutter: ^3.1.10
  flutter_markdown_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
